FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# phonedb

PhoneDB is a simple API allowing consumers to view mobile phone specifications.

The "Questions" Collection is a default example and should be removed before finalization.

## Phone Model Collection [/model]

### Retrieve All Models [GET]

+ Response 200 (application/json)

        [
            {
                "name": "LG LS998 V30+ TD-LTE / AS998  (LG Joan)",
                "general_attributes": {
                    "brand": "LG",
                    "model": "LS998 V30+ TD-LTE / AS998",
                    "release_date": "2017 Oct",
                    "announce_date": "2017 Sep",
                    "hardware_designer": "LG Electronics",
                    "manufacturer": "LG Electronics",
                    "codename": "LG Joan",
                    "market_countries": "USA",
                    "market_regions": "North America",
                    "vendor": "Sprint Nextel Corporation"
                },
                "physical_attributes": {
                    "width": "75.4 mm",
                    "height": "151.7 mm",
                    "depth": "7.3 mm",
                    "dimensions": "2.97x5.97x0.29 inches",
                    "mass": "158 g"
                },
                "software": {
                    "platform": "Android",
                    "os": "Google Android 7.1.2 (Nougat)",
                    "software_extras": "Voice Command, Navigation software, Virtual Reality (VR) support, Intelligent personal assisstent, Voice Recognition, Face Recognition"
                },
                "hardware": {
                    "cpu": {
                        "model": "Qualcomm Snapdragon 835 MSM8998, 2017, 64 bit, octa-core, 32 Kbyte I-Cache, 32 Kbyte D-Cache, 2048 Kbyte L2, 10 nm, Qualcomm Adreno 540 GPU",
                        "clock_speed": "2350 MHz"
                    },
                    "gpu": {
                        "model": "Qualcomm Adreno 540",
                        "clock_speed": "710 MHz"
                    },
                    "ram": {
                        "type": "LPDDR4x SDRAM 1866 MHz",
                        "capacity": "4.00 GiB RAM"
                    },
                    "nonvolatile_memory": {
                        "type": "Flash EEPROM",
                        "capacity": "128.0 GB ROM"
                    }
                }
            }
        ]

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }